vars: {
  d2-config: {
    layout-engine: elk
  }
}

pull_model: Pull Model (App Dev) {
  shape: sequence_diagram
  k8s: "Kubernetes (Flux)" {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FCompute%2FKubetnetes%20Engine.svg
  }
  gcp_cloudbuild: "Cloudbuild" {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FDeveloper%20Tools%2FCloud%20Build.svg
  }
  gcp_artifact_registry: "Artifact Registry" {
    shape: image
    icon: https://raw.githubusercontent.com/tcaky/WikiMeThis/main/media/google-cloud-icons/artifact_registry/artifact_registry.svg
  }
  github: "GitHub" {
    shape: image
    icon: https://icons.terrastruct.com/dev%2Fgithub.svg
  }
  infra: Infrastucture Change Monitoring {
    k8s -> github: Monitors for for infra changes
    k8s <- github: Pull infrastructure changes
    k8s -> k8s: Make infrastructure\nchanges a reality
  }
  application: Application Change Monitoring {
    gcp_cloudbuild -> github: Monitor for application changes
    gcp_cloudbuild <- github: Pull new changes to build container
    gcp_cloudbuild -> gcp_cloudbuild: Build new image
    gcp_cloudbuild -> gcp_artifact_registry: Push new image to\nArtifact Registry
    k8s <- gcp_artifact_registry: Pull and deploy new image into cluster
  }
}
